services:
  backend:
    build: .
    container_name: link_up_backend
    command: node index.js
    restart: always
    ports:
      - "3000:3000"
    networks: 
      - link_up_network
    depends_on:
      - mariadb
    volumes:
      - backend_data:/application

  mariadb:
    image: mariadb:latest
    container_name: link_up_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: linkupapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkup
    networks: 
      - link_up_network
    volumes:
      - /home/ablaiyli01/linkup_volumes/database:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: linkupminio
      MINIO_ROOT_PASSWORD: linkup2025
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - link_up_network

networks:
  link_up_network:
    driver: bridge

volumes:
  backend_data:
  minio_data: